# # syncer:
# #   extraArgs:
#       # - --tls-san=demo.vcluster-demo.com
#       # - --out-kube-config-server=https://demo.vcluster-demo.com
#     # - --tls-san=3.25.205.126,13.211.66.222
#     # - --tls-san=akaasif.people.aws.dev
#     # - --out-kube-config-server=http://akaasif.people.aws.dev
#     # - --kube-config-context-name=vcluster_prod-vcluster_prod-vcluster_default 
# sync:
#   ingresses:
#     enabled: true 
# #   isolation:
# #     enabled: true

isolation:
  enabled: false

  podSecurityStandard: baseline

  resourceQuota:
    enabled: true
    quota:
      requests.cpu: 10
      requests.memory: 20Gi
      requests.storage: "100Gi"
      requests.ephemeral-storage: 60Gi
      limits.cpu: 20
      limits.memory: 40Gi
      limits.ephemeral-storage: 160Gi
      services.nodeports: 4
      services.loadbalancers: 1
      count/endpoints: 40
      count/pods: 20
      count/services: 20
      count/secrets: 100
      count/configmaps: 100
      count/persistentvolumeclaims: 20
securityContext:
  runAsNonRoot: false


# sync:
#   services:
#     enabled: false
#   pods:
#     enabled: true
#     # Sync ephemeralContainers to host cluster
#     ephemeralContainers: true
#     # Sync readiness gates to host cluster
#     status: true
    
  networkPolicy:
    enabled: true
    outgoingConnections:
      ipBlock:
        cidr: 172.16.0.0/12
        except:
          - 100.64.0.0/10
          - 127.0.0.0/8
          - 10.0.0.0/8
          - 0.0.0.0/0
          - 192.168.0.0/16