apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata:
  name: demo-cluster-clusterissuer 
spec:
  acme:
    email: khanasif1@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx