apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: demo-vcluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: khanasif1/product_api:rc0.2
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
          - name: current_env
            value: dev-test
          - name: current_ver
            value: rc0.2
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: app-product
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

